### PR TITLE
Feat functionality

### PR DESCRIPTION
**Pull request by hsnice16**
### This PR will add code for the functionality of the quiz,
Now users can play the quiz.

In this PR, **255 additions 69 deletions** lines of code
- some files are only `index.js` that contains only 5 to 6 lines of code

### Please review this PR and give your feedback
---
#### [Live URL](https://react-marvels-quiz-git-feat-functionality-hsnice16.vercel.app/)

### CODE REVIEW

**Review by abhisheksahani-nova — APPROVED** [review]
Code looks subtle and clean .

Suggestion :- Naming for component like OtherPagesLink can be more specific .

**Comment by hsnice16** [comment]
> Code looks subtle and clean .
> 
> Suggestion :- Naming for component like OtherPagesLink can be more specific .

Thanks for suggesting this, Abhishek. I will see if I can name it something else.

And also, thanks for reviewing.

**Review by aayushjain-code — APPROVED** [review]
Good naming conventions and nice UI nothing to suggest as everything looks good to me you can merge it

**Comment by hsnice16** [comment]
Thank you for reviewing.

**Pull request merged**
